### ISSUE TITLE
gogui-twogtp -alternate writes incorrect result in the game records

### ISSUE THREAD

**Issue by Remi-Coulom** [Remi-Coulom/gogui#9] opened 2019-01-02 15:03 UTC
http://computer-go.org/pipermail/computer-go/2019-January/010962.html

> Thanks Remi! Nice to see that GoGui is still alive :-)
> 
> FYI the included version of gogui-twogtp has a bug (which has been around
> for many years) where the '-alternate' option causes incorrect results in
> the game records.
> 
> Happy New Year to all!
> Erik

**Comment by zakki** [comment] 2019-01-09 12:21
I think `TwoGtp` writes inverse result to a result `.dat` file by design.
https://github.com/Remi-Coulom/gogui/blob/master/src/net/sf/gogui/tools/twogtp/TwoGtp.java#L498

- straightforward result
  - SGF RE record

- Invert result
  - Result dat file

Is it better to reverse SGF comment or not?

**Comment by Remi-Coulom** [comment] 2019-01-09 13:59
Thanks for taking a look. I did not observe the problem that Erik mentions myself, so I am not sure what he was referring to. My impression is that the result in the SGF file should not be reversed (so that the sgf file is correct when considered in isolation), but it should be reversed in the dat file. If this is the current behaviour of gogui-twogtp, then I believe nothing should change.

**Comment by evdwerf** [comment] 2019-01-13 12:15
The problem is that if I take an SGF file from an odd game (colors reversed) then the result ('RE' field) is wrong (it does not match the actual colors when considered as a normal sgf file in isolation). Also, the comment in the root node could be considered misleading.

An easy way to spot such games is to look for resigned games and see who made the last move (the side that moved last normally did not resign). For example, if you see a game where white moved last, so ending with ";W[..])", together with "RE[B+R]", then something is wrong.

There have been other variants of this bug many years ago, some of which also messed up the statistics, but I believe those issues were solved a long time ago.

**Comment by Friday9i** [comment] 2019-01-14 09:49
I noticed the same: when colors are reversed, the SGF result is false (but this is corrected in the dat file, so that the .html file give the good result all together). Looking at who plays the last move indicates this is the other player who resigned ; -). That works, but it's a bit tricky to understand and to use it as it is. 
Ideally, that should be done the otherway: SGF giving the good result (and hence, no correction needed in the dat and html file to show the good overall result)
Thanks a lot for Gogui, that is a very useful tool! And that's very nice to now be able to play handicap games and games with specified openings, wonderful. A big thank you!
I did not use the tournament tool yet, but I will try it soon.

**Comment by Remi-Coulom** [comment] 2019-01-20 12:53
Thanks for your comments. We replicated the bug, and will fix it. @Sazuna will take care of it in about a week.

**Comment by Friday9i** [comment] 2019-01-26 13:30
Quick question: Leela Zero can use a random "seed".
When generating games, would it be possible to pass a different random seed for each game (in order to avoid/limit duplicate games)?
Cf for example a match game using a seed: http://zero.sjeng.org/viewmatch/438beef679e3d8027523f32f4b1da11a129c66e9341a3faac1cd08715235e48a?viewer=wgo where we can see the "-s 2824177286294292222" among the parameters.

**Comment by evdwerf** [comment] 2019-01-26 15:59
Restarting the engine on every new game could be a work-around (from twogtp's end), but IMO Leela Zero should just clear its cache on new games.

**Comment by alreadydone** [comment] 2019-01-26 17:38
@gcp won't clear the cache on clear_board because he thinks it's useful for analysis. Removing the lower limit on cache size should also eliminate duplicate games, but my comment regarding this got no response so I didn't submit a PR.

**Comment by gcp** [comment] 2019-01-26 19:20
Dedicated command to clear state and hashes would work, similarly to setoption name Clear Hash value true in UCI (which also has ucinew

**Comment by Friday9i** [comment] 2019-03-29 13:27
If I understand correctly, the issue has been fixed in a commit: would it be possible to push a new 1.5.1 windows version of Gogui taking these commits into account?

**Comment by Remi-Coulom** [comment] 2019-03-31 19:32
Yes, the issue is fixed. We are very busy with other projects at the moment, and won't have time to prepare a new release very soon. Maybe later in May.

**Comment by Friday9i** [comment] 2019-04-05 09:23
Thanks for your kind answer, good luck for your projects and I'll come back there from time to time to check if it is available ; -).
Merci !

**Comment by Remi-Coulom** [comment] 2019-04-24 15:27
We have just released 1.5.1 with the bug fix: https://github.com/Remi-Coulom/gogui/releases

**Comment by Friday9i** [comment] 2019-04-25 16:14
Sorry but I did not manage to make it run under windows 10 ; -(. While previous 1.5.0 was working perfectly.
I installed 1.5.1 in a separate folder (gogui3 vs gogui2 for the previous version), used the exact same command line with a bat file (linked to the gogui3 folder instead of gogui2, of course): the window opens and then close immediately without any error message (as it's very fast, just a fraction of a second, I made a movie of the window opening and closing: no message at all, I see the instruction from the bat file then it closes immediately). I de-installed and re-installed it without success. 
I tested again the 1.5.0 version and it still works perfectly, no issue.
Any feedback from other people, did you manage to make 1.5.1 work well under windows 10, any advice? Thanks a lot

**Comment by Remi-Coulom** [comment] 2019-04-26 12:55
Hi,

That's a strange error. I have just installed it successfully on a new machine and it works.

What is your version of Java?

Also: maybe try to flush your browser's cache or download with another browser: we had uploaded a bad version first. It stayed for a very short time, but you may have downloaded it.

Rémi

**Comment by Friday9i** [comment] 2019-04-26 14:52
Ok, I'll download it again and will reinstall it this week-end.
And of course I'll post a detailed update (on the problem or, hopefully, on the solution ; -).
Thanks a lot

**Comment by Remi-Coulom** [comment] 2019-05-18 06:56
I can confirm the problem. We fixed it one week ago. The new installer should be OK now.

**Comment by Friday9i** [comment] 2019-05-19 20:46
Cool, I just noticed your post and installed the latest version: I can confirm it now works perfectly!
Wonderful, thanks a lot

**Comment by lp200** [comment] 2021-12-24 22:24
The alternate mode in 1.5.1 still has bugs.
 PB[name1]PW[name2] in the SGF file remains the same.

**Closed** 2022-10-09 19:20 UTC

**Comment by tomtseng** [comment] 2022-10-09 19:24
> The alternate mode in 1.5.1 still has bugs. PB[name1]PW[name2] in the SGF file remains the same.

Should be fixed now in with PR #30 merged
